# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82e983150aa3e53101145ef54cc5c09aff0c07cac536d7caf723d9ad8a3995804a58e6af9a1361b70881f58951c6e53139126eb7853c33e3e8d78871920afe79

test:
  secret_key_base: 793eb114784c396cbb18126cee13206b9ca16b89973a286a8b43253d5fa04c688a65308427a9c9fc0ec8c8f1d95dc6d6e0784987f02a6a6116777c575f477959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
